[theme]
primaryColor="#E50914"
backgroundColor="#141414"
secondaryBackgroundColor="#333333"
textColor="#FFFFFF"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats=false
